name: workflow
run-name: ${{ github.actor }} is testing hexlet-ci-app workflow 🚀
on: [push]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      # Клонируем репозиторий
      - uses: actions/checkout@v3
      # Устанавливаем Node.js
      - uses: actions/setup-node@v3
      - run: npm install
      - run: npm run build
      - run: npm test
      - run: npx eslint .
