name: workflow
run-name: ${{ github.actor }} is testing hexlet-ci-app workflow 🚀
on: [push]
jobs:
  job_0:
    runs-on: ubuntu-latest
    steps:
      - run: make setup
      # - run: npm install
      # - run: npm run build
      # - run: npm test
      # - run: npx eslint .
